site_name: Linkedin Games Solvers
repo_url: https://github.com/rodrigo-cl-porto/linkedin-games-solvers
repo_name: linkedin-games-solvers
edit_uri: tree/main/docs

theme:
  name: readthedocs
  logo: assets/logo-dark.svg
  favicon: assets/logo.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: amber
      toggle:
        icon: material/weather-night
        name: Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Light Mode

markdown_extensions:
  - attr_list

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            summary: true
            docstring_style: google
            group_by_category: true
            inherited_members: true
            show_source: false
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: false
