[project]
name = "Solving-LinkedIn-Games-by-Linear-Optimization"
version = "0.1.3"
description = "A Python package for solving LinkedIn games using linear optimization techniques."
authors = [{ name = "Rodrigo Celso de Lima Porto", email = "rodrigo.cl.porto@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE.md" }
requires-python = ">=3.13"
dependencies = [
    "gurobipy>=13.0.1",
    "highspy>=1.14.0",
    "matplotlib>=3.10.8",
    "networkx>=3.6.1",
    "pyomo>=6.10.0",
]

[dependency-groups]
dev = [
    "ipywidgets>=8.1.8",
    "jupyter-book>=2.1.4",
    "jupyterlab>=4.5.6",
    "jupyterlab-myst>=2.6.0",
    "pytest>=9.1.1",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["linkedin_games"]
