[project]
name = "linkedin-games-playground"
version = "0.1.0"
description = "This branch is reserved to be hosted on Binder to serve as a Jupyter Lab playground."
authors = [{ name = "Rodrigo C. L. Porto", email = "rodrigo.cl.porto@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE.md" }
requires-python = ">=3.13"
dependencies = [
    "ipywidgets>=8.1.8",
    "jupyterlab>=4.6.2",
    "linkedin-games>=0.1.0rc3",
]

[tool.hatch.build.targets.wheel]
bypass-selection = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
