name: Publish to PyPI

on:
  release:
    types: [published] # Triggers when a release is created on GitHub

jobs:
  pypi-publish::
    name: build and publish the python package to pypi
    runs-on: ubuntu-latest

    # REQUIRED: mandatory permissions to get OIDC working.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: copy the repo to virtual server
        uses: actions/checkout@v6
        with:
          # Avoid copying unnecessary folder to virtual environment.
          sparse-checkout: |
            /*
            !/docs
            !/book
            !/tests

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: build package
        run: uv build --no-sources

      - name: publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # uses: pypa/gh-action-pypi-publish@3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f
